import re

class ASSSubtitleGenerator:
    """ASS 자막 생성기

    - SRT와 동일한 세그먼트/단어 정보를 받아 ASS 포맷으로 변환합니다.
    - 감정(emotion)에 따라 PrimaryColour를 동적으로 오버라이드합니다.
    - 단어별 하이라이트는 \1c(색상), \fs(폰트 크기) 태그로 간단히 표현합니다.
    """

    def __init__(self, subtitle_settings: dict):
        self.default_font_size = subtitle_settings['font']['default_size']
        self.min_font_size = subtitle_settings['font']['min_size']
        self.max_font_size = subtitle_settings['font']['max_size']
        self.emotion_colors = subtitle_settings['hex_colors']['emotion_colors']
        self.default_color = subtitle_settings['hex_colors']['default_color']
        self.highlight_color = subtitle_settings['hex_colors']['highlight_color']

    @staticmethod
    def _hex_to_ass_bgr(hex_color: str) -> str:
        """#RRGGBB -> &H00BBGGRR (ASS BGR with alpha=00)
        잘못된 형식이면 기본 흰색으로 처리합니다.
        """
        if not isinstance(hex_color, str):
            hex_color = "#FFFFFF"
        m = re.fullmatch(r"#?([0-9A-Fa-f]{6})", hex_color.strip())
        if not m:
            # 짧은 #RGB를 확장 시도
            m3 = re.fullmatch(r"#?([0-9A-Fa-f]{3})", hex_color.strip())
            if m3:
                rgb = m3.group(1)
                r, g, b = (c*2 for c in rgb)
            else:
                r, g, b = ("FF", "FF", "FF")
        else:
            rgb = m.group(1)
            r, g, b = rgb[0:2], rgb[2:4], rgb[4:6]
        # ASS는 BGR 순서, 선행 00은 alpha(완전 불투명)
        return f"&H00{b.upper()}{g.upper()}{r.upper()}"

    @staticmethod
    def _format_ass_time(seconds: float) -> str:
        # h:mm:ss.cs (centiseconds)
        if seconds < 0:
            seconds = 0.0
        h = int(seconds // 3600)
        m = int((seconds % 3600) // 60)
        s = int(seconds % 60)
        cs = int(round((seconds - int(seconds)) * 100))
        if cs == 100:
            s += 1
            cs = 0
        return f"{h:d}:{m:02d}:{s:02d}.{cs:02d}"

    def _ass_header(self) -> str:
        primary = self._hex_to_ass_bgr(self.default_color)
        # 기본 스타일 하나만 두고, 라인마다 override 태그로 색/크기를 조정합니다.
        header = [
            "[Script Info]",
            "; Script generated by STT_KR livecaption",
            "ScriptType: v4.00+",
            "PlayResX: 1920",
            "PlayResY: 1080",
            "ScaledBorderAndShadow: yes",
            "",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "+
            "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding",
            f"Style: Default, Arial, {self.default_font_size}, {primary}, &H000000FF, &H3C000000, &H64000000, 0, 0, 0, 0, "+
            "100, 100, 0, 0, 1, 2, 0.5, 2, 10, 10, 20, 1",
            "",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text"
        ]
        return "\n".join(header) + "\n"

    def segments_to_ass(self, segments: list, output_path: str):
        with open(output_path, "w", encoding="utf-8-sig") as f:
            f.write(self._ass_header())

            for segment in segments:
                words = segment.get("words", [])
                speaker = "[" + segment.get("speaker", "Unknown") + "]"
                emotion = segment.get('emotion', 'neutral')
                # 감정 색상 → ASS 색
                emotion_hex = self.emotion_colors.get(emotion, self.default_color)
                emotion_ass = self._hex_to_ass_bgr(emotion_hex)

                prev_end = None
                for i, w in enumerate(words):
                    if "start" not in w or "end" not in w:
                        continue
                    w_start = w["start"] if prev_end is None else prev_end
                    w_end = w["end"]
                    prev_end = w_end

                    # 하이라이트 색/크기
                    word_text = w.get("word", "")
                    word_type = w.get("type", 1)  # 0 whisper, 1 normal, 2 shout (없으면 기본)
                    if word_type == 0:
                        fs = self.min_font_size
                    elif word_type == 2:
                        fs = self.max_font_size
                    else:
                        fs = self.default_font_size

                    # 라인 텍스트 구성: 감정색을 기본으로 두고, 단어는 강조색으로 오버라이드
                    # \N으로 화자 라벨과 본문 줄바꿈
                    base_color_tag = f"{{\\1c{emotion_ass}}}"
                    # 강조 단어는 highlight_color 사용
                    hl_ass = self._hex_to_ass_bgr(self.highlight_color)
                    word_tag = f"{{\\1c{hl_ass}\\fs{fs}}}{word_text}{{\\r}}"  # {\r}로 스타일 리셋
                    line_text = f"{base_color_tag}{speaker}\\N{word_tag}"

                    start_ts = self._format_ass_time(w_start)
                    end_ts = self._format_ass_time(w_end)

                    dialogue = (
                        f"Dialogue: 0,{start_ts},{end_ts},Default,,0,0,0,,{line_text}\n"
                    )
                    f.write(dialogue)

        print(f"ASS 파일이 저장되었습니다: {output_path}")
