# Generated by Django 5.2.6 on 2025-11-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery 작업 ID')),
                ('status', models.CharField(default='PENDING', max_length=50, verbose_name='작업 상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 작업 목록',
                'verbose_name_plural': '사용자 작업 목록',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='STT_KR_SAMPLE_WEB.usertask', verbose_name='Celery 작업')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='파일명')),
                ('srt_subtitle', models.TextField(blank=True, null=True, verbose_name='자막 내용')),
                ('config', models.JSONField(default=dict, verbose_name='설정 데이터')),
                ('segment', models.JSONField(default=dict, verbose_name='자막 데이터')),
            ],
            options={
                'verbose_name': '작업 정보',
                'verbose_name_plural': '작업 정보',
            },
        ),
    ]
