# Generated by Django 5.2 on 2025-10-18 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Celery 작업 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 작업 목록',
                'verbose_name_plural': '사용자 작업 목록',
            },
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='STT_KR_SAMPLE_WEB.usertask', verbose_name='Celery 작업')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='자막 내용')),
                ('config', models.JSONField(default=dict, verbose_name='설정 데이터')),
            ],
            options={
                'verbose_name': '작업 정보',
                'verbose_name_plural': '작업 정보',
            },
        ),
    ]
