# Generated by Django 5.2 on 2025-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STT_KR_SAMPLE_WEB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='status',
            field=models.CharField(default='PENDING', max_length=50, verbose_name='작업 상태'),
        ),
    ]
