# Generated by Django 5.2.6 on 2025-10-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STT_KR_SAMPLE_WEB', '0002_usertask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='task',
            new_name='task_id',
        ),
    ]
