# Generated by Django 5.2.6 on 2025-10-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STT_KR_SAMPLE_WEB', '0003_rename_task_taskinfo_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='task_id',
            new_name='task',
        ),
    ]
