# Generated by Django 5.2.6 on 2025-11-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STT_KR_SAMPLE_WEB', '0004_rename_task_id_taskinfo_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskinfo',
            old_name='subtitle',
            new_name='srt_subtitle',
        ),
        migrations.AddField(
            model_name='taskinfo',
            name='segment',
            field=models.JSONField(default=dict, verbose_name='자막 데이터'),
        ),
    ]
